name: Build and SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java 17 (same as your config)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Give execute permission to gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Step 4: Run Gradle build and SonarQube analysis
      - name: Build and run SonarQube
        run: ./gradlew build sonar --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
